language: node_js
sudo: false
node_js:
  - "6.11.1"
#addons:
#  firefox: latest
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-beta
install:
  - npm install
# TODO: Service account's Key
#  - cd functions && npm install && cd ..
  - patch -p0 < polymer-cli-issue-701.patch
  - perl -pi -e 's/\/\/# sourceMappingURL.*//' components/firebase/firebase-auth.js
script:
# - xvfb-run polymer test
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy:travis
  on:
    branch: master
    tags: true
